name: asivane-k8s-korkshop

services:
  web:
    container_name: web
    depends_on:
      - db
      - cache
    image: aseivane/k8s-workshop:0.1.0
    networks:
      - workshop
    ports:
      - "80:5000"
    restart: always

  db:
    container_name: postgres
    environment:
      - POSTGRES_USER=sql-user
      - POSTGRES_PASSWORD=sql-password
    expose:
      - "5432"
    image: postgres:16.2-alpine3.19
    networks:
      - workshop
    restart: always

  cache:
    container_name: redis
    command: redis-server --save 20 1 --loglevel warning
    expose:
      - "6379"
    image: redis:7.2.4-alpine
    networks:
      - workshop
    restart: always

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  workshop:
    name: workshop
    external: true